# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=7)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=25)),
                ('nationality', models.CharField(max_length=40)),
                ('number_of_Adult_travellers', models.IntegerField()),
                ('number_of_Children_travellers', models.IntegerField()),
                ('travelling_From', models.CharField(max_length=40)),
                ('travelling_To', models.CharField(max_length=40)),
                ('arrival_city', models.CharField(max_length=40)),
                ('arrival_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
