# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='arrival_city',
            field=models.CharField(max_length=50),
        ),
    ]
