# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170615_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='purpose',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
