# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170612_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='DOB',
            new_name='age',
        ),
    ]
