# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170620_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='password1',
            new_name='conform_password',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='password2',
            new_name='password',
        ),
    ]
