# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170620_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('phone', models.IntegerField()),
                ('nationality', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('conform_password', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
