# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170620_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.DateField(),
        ),
    ]
