# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170613_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=7)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=25)),
                ('nationality', models.CharField(max_length=40)),
                ('number_of_Adult_travellers', models.IntegerField()),
                ('number_of_Children_travellers', models.IntegerField()),
                ('travelling_From', models.CharField(max_length=40)),
                ('travelling_To', models.CharField(max_length=40)),
                ('arrival_date', models.DateField()),
            ],
        ),
    ]
