# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170622_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(max_length=25),
        ),
    ]
