# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='BookNow',
        ),
    ]
