# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170622_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
