# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170622_1443'),
        ('app', '0004_auto_20170622_1522'),
    ]

    operations = [
    ]
